name: KICS Scan for NodeGoat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Optional, allows manual triggering

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Ensure results directory exists
        run: mkdir -p ./results

      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@v2.1.3
        with:
          path: '.'
          output_path: ./results
          additional_args: '--log-level DEBUG'

      - name: Verify results
        run: |
          if [ ! -f ./results/results.json ]; then
            echo "KICS scan did not generate results.json"
            exit 1
          else
            echo "Scan completed successfully"
          fi

      - name: Upload KICS Scan Results as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: kics-scan-results
          path: ./results/results.json

