name: KICS Scan for NodeGoat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Optional, allows manual triggering

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create output directory
        run: mkdir -p $HOME/Documents/Dev/NodeGoat/results  # Use $HOME to refer to the home directory

      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@v2.1.3
        with:
          path: '/'
          output_path: $HOME/Documents/Dev/NodeGoat/results  # Set output path to the desired location
          args: '--verbose --no-progress --output-format json'

      - name: List files in output directory
        run: ls -al $HOME/Documents/Dev/NodeGoat/results  # List files in the results directory

      - name: Upload KICS Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kics-results
          path: $HOME/Documents/Dev/NodeGoat/results  # Upload results as artifact
