name: KICS Scan for NodeGoat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Optional, allows manual triggering

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Scan IaC with KICS
                    
      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v2.1.3
        with:
          # Paths to scan, here we use the entire repository
          path: '.'
          output_path: myResults/

      # Display the results in JSON format
      - name: Display KICS results
        run: |
          cat myResults/results.json
