name: KICS Scan for NodeGoat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Optional, allows manual triggering

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Ensures the full commit history is available
          fetch-depth: 0

      # Set up KICS scan
      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@v2.1.3
        with:
          # Path to scan; using '.' to scan the entire repository
          path: '/'
          # Output location for scan results
          output_path: ./results
          # Optional: Specify additional parameters if needed, such as cloud provider or secrets scanning
          # Example:
          # --cloud-provider aws,azure
          # --disable-secrets
